
(********************
 *
 * Converts STRING to INT
 *
*********************)
FUNCTION STRING_TO_INT : INT
VAR_INPUT
	in : STRING;
END_VAR
unimplemented('STRING_TO_INT');
END_FUNCTION
(********************
 *
 * Converts INT to STRING
 *
*********************)
FUNCTION INT_TO_STRING : STRING
VAR_INPUT
	in : INT;
END_VAR
unimplemented('INT_TO_STRING');
END_FUNCTION

(********************
 *
 * Converts UDINT to DT
 *
*********************)
FUNCTION UDINT_TO_DT : DT
VAR_INPUT
	in : UDINT;
END_VAR
unimplemented('UDINT_TO_DT');
END_FUNCTION

(********************
 *
 * Converts DWORD to TOD
 *
*********************)
FUNCTION DWORD_TO_TOD : TOD
VAR_INPUT
	in : DWORD;
END_VAR
unimplemented('DWORD_TO_TOD');
END_FUNCTION

(********************
 *
 * Converts DT to UDINT
 *
*********************)
FUNCTION DT_TO_UDINT : UDINT
VAR_INPUT
	in : DT;
END_VAR
unimplemented('DT_TO_UDINT');
END_FUNCTION

(********************
 *
 * Converts DWORD to DT
 *
*********************)
FUNCTION DWORD_TO_DT : DT
VAR_INPUT
	in : DWORD;
END_VAR
unimplemented('DWORD_TO_DT');
END_FUNCTION

(********************
 *
 * Converts TIME to INT
 *
*********************)
FUNCTION TIME_TO_INT : INT
VAR_INPUT
	in : TIME;
END_VAR
unimplemented('TIME_TO_INT');
END_FUNCTION

(********************
 *
 * Converts TOD to DWORD
 *
*********************)
FUNCTION TOD_TO_DWORD : DWORD
VAR_INPUT
	in : TOD;
END_VAR
unimplemented('TOD_TO_DWORD');
END_FUNCTION

(********************
 *
 * Converts DWORD to DATE
 *
*********************)
FUNCTION DWORD_TO_DATE : DATE
VAR_INPUT
	in : DWORD;
END_VAR
unimplemented('DWORD_TO_DATE');
END_FUNCTION

(********************
 *
 * Converts DATE to UDINT
 *
*********************)
FUNCTION DATE_TO_UDINT : UDINT
VAR_INPUT
	in : DATE;
END_VAR
unimplemented('DATE_TO_UDINT');
END_FUNCTION

(********************
 *
 * Converts UDINT to DATE
 *
*********************)
FUNCTION UDINT_TO_DATE : DATE
VAR_INPUT
	in : UDINT;
END_VAR
unimplemented('UDINT_TO_DATE');
END_FUNCTION

(********************
 *
 * Converts DINT to TOD
 *
*********************)
FUNCTION DINT_TO_TOD : TOD
VAR_INPUT
	in : DINT;
END_VAR
unimplemented('DINT_TO_TOD');
END_FUNCTION

(********************
 *
 * Converts TOD to DINT
 *
*********************)
FUNCTION TOD_TO_DINT : DINT
VAR_INPUT
	in : TOD;
END_VAR
unimplemented('TOD_TO_DINT');
END_FUNCTION

(********************
 *
 * Converts DATE to DWORD
 *
*********************)
FUNCTION DATE_TO_DWORD : DWORD
VAR_INPUT
	in : DATE;
END_VAR
unimplemented('DATE_TO_DWORD');
END_FUNCTION


(********************
 *
 * Converts BYTE to REAL
 *
*********************)
FUNCTION BYTE_TO_REAL : REAL
VAR_INPUT
	in : BYTE;
END_VAR
unimplemented('BYTE_TO_REAL');
END_FUNCTION

(********************
 *
 * Converts WORD to REAL
 *
*********************)
FUNCTION WORD_TO_REAL : REAL
VAR_INPUT
	in : WORD;
END_VAR
unimplemented('WORD_TO_REAL');
END_FUNCTION

(********************
 *
 * Converts TIME to DINT
 *
*********************)
FUNCTION TIME_TO_DINT : DINT
VAR_INPUT
	in : TIME;
END_VAR
unimplemented('TIME_TO_DINT');
END_FUNCTION

(********************
 *
 * Converts REAL to TIME
 *
*********************)
FUNCTION REAL_TO_TIME : TIME
VAR_INPUT
	in : REAL;
END_VAR
unimplemented('REAL_TO_TIME');
END_FUNCTION

(********************
 *
 * Converts DT to DWORD
 *
*********************)
FUNCTION DT_TO_DWORD : DWORD
VAR_INPUT
	in : DT;
END_VAR
unimplemented('DT_TO_DWORD');
END_FUNCTION


(********************
 *
 * Converts DWORD to TIME
 *
*********************)
FUNCTION DWORD_TO_TIME : TIME
VAR_INPUT
	in : DWORD;
END_VAR
unimplemented('DWORD_TO_TIME');
END_FUNCTION

(********************
 *
 * Converts TIME to DWORD
 *
*********************)
FUNCTION TIME_TO_DWORD : DWORD
VAR_INPUT
	in : TIME;
END_VAR
unimplemented('TIME_TO_DWORD');
END_FUNCTION

(********************
 *
 * Converts TIME to REAL
 *
*********************)
FUNCTION TIME_TO_REAL : REAL
VAR_INPUT
	in : TIME;
END_VAR
unimplemented('TIME_TO_REAL');
END_FUNCTION
